
import "./globals.css";
import { ToastContainer, toast } from "react-toastify";
import Nav from "@/component/Nav";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
   
  return (
    <html lang="en">
      <body>
        <Nav />
        {children}
        <ToastContainer
          position="bottom-left"
          autoClose={4000}
          hideProgressBar={false}
          newestOnTop={true}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
        />
      </body>
    </html>
  );
}
